DROP TABLE IF EXISTS User;
CREATE TABLE User (
    username TEXT PRIMARY KEY NOT NULL,
    password TEXT NOT NULL,
    balance REAL NOT NULL
);

DROP TABLE IF EXISTS Diginote;
CREATE TABLE Diginote (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    owner TEXT NOT NULL,
    FOREIGN KEY (owner) REFERENCES User(username)
);

DROP TABLE IF EXISTS BuyOrder;
CREATE TABLE BuyOrder (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user TEXT NOT NULL,
	price REAL NOT NULL,
	amount INTEGER NOT NULL,
	date TEXT NOT NULL,
    FOREIGN KEY (user) REFERENCES User(username)
);

DROP TABLE IF EXISTS SellOrder;
CREATE TABLE SellOrder (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user TEXT NOT NULL,
	price REAL NOT NULL,
	amount INTEGER NOT NULL,
	date TEXT NOT NULL,
    FOREIGN KEY (user) REFERENCES User(username)
);